config/routes.rb
Rails.application.routes.draw do
  resources :buscas, only: [:create]
  resources :links
  resources :perfils
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "perfils#index"
end

app/models/link.rb
class Link < ApplicationRecord

    belongs_to :perfil

    before_validation :padronizar_url
    validates :url_original, uniqueness: true, presence: true
    validates :perfil_id, uniqueness: true, presence: true
    before_save :gerar_url_curta

    def gerar_url_curta
        begin
            self.url_curta = UrlCurtaService.new.encurtar(self.url_original)
        rescue 
            self.url_curta = link_nem_tao_curto_mas_unico
        end
    end

    private
    
    def link_nem_tao_curto_mas_unico
        "fretadissimo.com/" + Base64.encode64((Time.now - Time.parse('2025-01-01 00:00:00')).to_i.to_s(32))
    end

    # Força um padrão (https://github.com/perfil) porque existem muitas variações para chegar ao mesmo perfil e redundância não é bom
    # exemplos: 
    # up/downcase  GITHUB.COM, github.com, GiThUb.CoM
    # prefixos https://github.com/matz, https://www.github.com/matz, www.github.com/matz, github.com/matz
    # parâmetros https://github.com/matz?tab=repositories https://github.com/matz?tab=projects
    # o importante é sempre salvar com o mesmo padrão, e se mudar o padrão que salva, mudar os registros anteriores
    def padronizar_url
        if url_original.present?
            nome_perfil = self.url_original.scan(/github.com\/([a-zA-Z0-9]+)\/?/i).flatten
            raise "URL inválida" if nome_perfil.count != 1

            self.url_original = "https://github.com/#{nome_perfil.first.downcase}"
        end
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_path, notice: "Link was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.expect(link: [ :url_curta, :url_original ])
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url_curta, style: "display: block" %>
    <%= form.text_field :url_curta %>
  </div>

  <div>
    <%= form.label :url_original, style: "display: block" %>
    <%= form.text_field :url_original %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>Url curta:</strong>
    <%= link.url_curta %>
  </p>

  <p>
    <strong>Url original:</strong>
    <%= link.url_original %>
  </p>

</div>

app/views/links/edit.html.erb
<% content_for :title, "Editando link" %>

<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Links" %>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", link %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_link_path %>

app/views/links/new.html.erb
<% content_for :title, "New link" %>

<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>