config/routes.rb
Rails.application.routes.draw do
  resources :buscas, only: [:create]
  resources :links
  resources :perfils
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "perfils#index"
end

app/models/perfil.rb
class Perfil < ApplicationRecord
    has_one :link, dependent: :destroy
    has_many :buscas, dependent: :destroy
    accepts_nested_attributes_for :link

    def self.procurar(texto)
        ilike = formar_ilike(texto)
        self.where("nome ilike ? or nome_usuario ilike ? or organizacao ilike ? or localizacao ilike ?", ilike, ilike, ilike, ilike)
    end

    def ultima_busca
        Busca.where(perfil_id: self.id).order(created_at: :desc).limit(1).first
    end

    private

    def self.formar_ilike(texto)
        "%" + sanitize_sql_like(texto) + "%"
    end
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  before_action :set_perfil, only: %i[ show edit update destroy ]

  # GET /perfils or /perfils.json
  def index
    if procurar_params[:texto].present?
      @perfils = Perfil.procurar(procurar_params[:texto])
    else
      @perfils = Perfil.all
    end
  end

  # GET /perfils/1 or /perfils/1.json
  # não está sendo utilizado, ao verificar o registro prefiro poder alterá-lo
  # o show pode ser utilizado quando não se espera que o usuário o edite, como um card para hover ou algo do gênero
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
    @perfil.link = @perfil.build_link
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils or /perfils.json
  def create
    @resultado = PerfilInteractor.call perfil_params: perfil_params
    @perfil = @resultado.perfil

    respond_to do |format|
      if @resultado.status
        format.html { redirect_to edit_perfil_path(@perfil), notice: "Sucesso!" }
        format.json { render :edit, status: :created, location: @perfil }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resultado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1 or /perfils/1.json
  def update
    respond_to do |format|
      @resultado = PerfilInteractor.call perfil_params: perfil_params, id: params[:id]
      #if @perfil.update(perfil_params)
      if @resultado.status
        format.html { redirect_to edit_perfil_path(@perfil), notice: "Perfil atualizado.", status: :see_other }
        format.json { render :edit, status: :ok, location: @perfil }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resultado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1 or /perfils/1.json
  def destroy
    #@perfil.destroy!

    respond_to do |format|
      format.html { redirect_to perfils_path, notice: "Perfil deletado.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def perfil_params
      params.require(:perfil).permit([:id, :nome], link_attributes: [:id, :url_original])
    end

    def procurar_params
      params.permit(:texto)
    end
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/views/perfils/_form.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with(model: perfil, class: 'form') do |form| %>
  <%= form.hidden_field :id, value: perfil.id %>

  <% if perfil.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(perfil.errors.count, "error") %> </h2>

      <ul>
        <% @resultado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='principal flex-div'>
      <div>
        <%= image_tag(perfil.url_foto || "snoopy.png", { class: 'avatar' }) %>
        <% if perfil.id.present? %>
          <div style='text-align: center;'>
            <h2 id='nome_avatar'> <%= perfil.nome %> </h2>
          </div>
          <%= render "ultima_busca", busca: perfil.ultima_busca %>
        <% end %>
      </div>
    
      <div style="align-self: flex-end">
        <div>
          <%= form.label :nome, style: "display: block" %>
          <%= form.text_field :nome, onchange: "muda_nome_avatar();" %>
        </div>

        <!-- nested link -->
        <%= form.fields_for :link do |link_form| %>
          <%= link_form.label :url_original, style: "display: block" %>
          <%= link_form.text_field :url_original, value: perfil.link.url_original %>

          <% unless perfil.id.nil? %>
            <%= link_form.hidden_field :id, value: perfil.link.id %>
            <%= link_form.label :url_curta, style: "display: block" %>
            <%= link_form.text_field :url_curta, value: perfil.link.url_curta, readonly: true %>
          <% end %>
        <% end %>

        <!-- Na criação esconde os campos que serão buscados -->
        <% unless perfil.id.nil? %>
          <div>
            <%= form.label :nome_usuario, style: "display: block" %>
            <%= form.text_field :nome_usuario, readonly: true %>
          </div>

          <div>
            <%= form.label :seguidores, style: "display: block" %>
            <%= form.text_field :seguidores, readonly: true %>
          </div>

          <div>
            <%= form.label :seguindo, style: "display: block" %>
            <%= form.text_field :seguindo, readonly: true %>
          </div>

          <div>
            <%= form.label :estrelas, style: "display: block" %>
            <%= form.text_field :estrelas, readonly: true %>
          </div>

          <div>
            <%= form.label :contribuicoes, style: "display: block" %>
            <%= form.text_field :contribuicoes, readonly: true %>
          </div>

          <div>
            <%= form.label :url_foto, style: "display: block" %>
            <%= form.text_field :url_foto, readonly: true %>
          </div>

          <div>
            <%= form.label :organizacao, style: "display: block" %>
            <%= form.text_field :organizacao, readonly: true %>
          </div>

          <div>
            <%= form.label :localizacao, style: "display: block" %>
            <%= form.text_field :localizacao, readonly: true %>
          </div>
        <% end %> <!-- unless id --> 

        <div class='flex-div'>
          <div>
            <%= form.submit perfil.id.nil? ? "Adicionar" : "Salvar", class: 'botao' %>
          </div>

<% end %> <!-- form for perfil -->
      <% if perfil.id.present? %>
          <div>
            <%= button_to "Atualizar", buscas_path(), method: :post, params: { busca: { perfil_id: perfil.id }}, title: 'Buscar novamente no Github', class: 'botao' %>
          </div>
          <div>
            <%= link_to "&#x1f5d1;".html_safe, perfil, title: 'deletar', data: { turbo_method: :delete, turbo_confirm: "Deseja mesmo deletar?" }, class: 'botao' %>
          </div>
      <% end %>
      </div> <!-- div dos botões -->
    </div> <!-- conteúdo div direita -->
  </div> <!--table-div principal -->

  <script>
    function muda_nome_avatar(){
      novo_nome = document.getElementById('perfil_nome').value;
      document.getElementById('nome_avatar').innerHTML = novo_nome;
    }
  </script>

app/views/perfils/_linha_perfil.html.erb
<div class='table-tr'>
    <div class='table-td'>
        <%= perfil.nome %>
    </div>
    <div class='table-td'>
        <%= link_to perfil.link.url_curta, perfil.link.url_original, target: "_blank" %>
    </div>
    <div class='table-td'>
        <%= circulo_status(perfil.ultima_busca.status) %> <%= link_to "Editar", edit_perfil_path(perfil), class: "botao" %>
    </div>
</div>

app/views/perfils/_perfil.html.erb
<div id="<%= dom_id perfil %>">
  <p>
    <strong>Nome:</strong>
    <%= perfil.nome %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= perfil.link.url_curta %>
  </p>

  <p>
    <strong>Nome Usuario:</strong>
    <%= perfil.nome_usuario %>
  </p>

  <p>
    <strong>Seguidores:</strong>
    <%= perfil.seguidores %>
  </p>

  <p>
    <strong>Seguindo:</strong>
    <%= perfil.seguindo %>
  </p>

  <p>
    <strong>Estrelas:</strong>
    <%= perfil.estrelas %>
  </p>

  <p>
    <strong>Contribuicoes:</strong>
    <%= perfil.contribuicoes %>
  </p>

  <p>
    <strong>Url foto:</strong>
    <%= perfil.url_foto %>
  </p>

  <p>
    <strong>Organizacao:</strong>
    <%= perfil.organizacao %>
  </p>

  <p>
    <strong>Localizacao:</strong>
    <%= perfil.localizacao %>
  </p>

</div>

app/views/perfils/_ultima_busca.html.erb
<div>
    <b>Última busca</b>
    <br>
    <small><%= busca.updated_at.strftime("%d/%m/%Y %H:%M:%S") %></small><br>
    Status: <%= circulo_status(busca.status) %> <%= busca.status %><br><br>
    Total Buscas: <%=busca.perfil.buscas.count %>
</div>

app/views/perfils/edit.html.erb
<% content_for :title, "Editar perfil" %>

<div class='flex-div' style="width: 40%;">
  <h1>Editando perfil</h1>
  <div class="alinhar-direita">
    <%= link_to "Voltar", perfils_path, class: 'botao' %>
  </div>
</div>

<%= render "form", perfil: @perfil %>

app/views/perfils/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Perfils" %>

<h1>Perfis</h1>

<div class='principal'>
  
  <div class='flex-div'>
    <div>
      <%= form_with url: perfils_path, method: :get do |form| %>
        <%= form.search_field :texto, value: params[:texto] %>
        <%= form.submit "Procurar", class: 'botao' %>
      <% end %>
    </div>
    <div class='alinhar-direita'>
      <%= link_to "Adicionar perfil", new_perfil_path, class: 'botao' %>
    </div>
  </div>
  

  <div id="perfils" class='table-div'>
      <div class='table-tr'>
          <div class='table-td'>
            <strong> Nome </strong>
          </div>
          <div class='table-td'>
            <strong> Link Github </strong>
          </div>
      </div>
      <% @perfils.each do |perfil| %>
        <%= render "linha_perfil", perfil: perfil %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/perfils/new.html.erb
<% content_for :title, "New perfil" %>

<div class='flex-div' style="width: 40%;">
  
    <h1>Adicionar perfil</h1>
    <div class="alinhar-direita">
      <%= link_to "Voltar", perfils_path, class: 'botao' %>
    </div>
  
</div>

<%= render "form", perfil: @perfil %>

<br>

app/views/perfils/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @perfil %>

<div>
  <%= link_to "Edit this perfil", edit_perfil_path(@perfil) %> |
  <%= link_to "Back to perfils", perfils_path %>

  <%= button_to "Destroy this perfil", @perfil, method: :delete %>
</div>