config/routes.rb
Rails.application.routes.draw do
  resources :buscas, only: [:create]
  resources :links
  resources :perfils
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "perfils#index"
end

app/models/busca.rb
class Busca < ApplicationRecord
    belongs_to :perfil
    enum :status, [:pendente, :processando, :completa, :erro]
end

app/controllers/buscas_controller.rb
class BuscasController < ApplicationController
  before_action :set_busca, only: %i[ show edit update destroy ]

  # GET /buscas or /buscas.json
  def index
    @buscas = Busca.all
  end

  # GET /buscas/1 or /buscas/1.json
  def show
  end

  # GET /buscas/new
  def new
    @busca = Busca.new
  end

  # GET /buscas/1/edit
  def edit
  end

  # POST /buscas or /buscas.json
  def create
    @busca = Busca.new(busca_params)

    respond_to do |format|
      if @busca.save
        BuscaJob.new.perform(@busca.id)
        format.html { redirect_to edit_perfil_path(@busca.perfil_id), notice: "Nova busca criada." }
        format.json { render edit_perfil_path(@busca.perfil_id), status: :created, location: @busca }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @busca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buscas/1 or /buscas/1.json
  def update
    respond_to do |format|
      if @busca.update(busca_params)
        format.html { redirect_to @busca, notice: "Busca was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @busca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @busca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buscas/1 or /buscas/1.json
  def destroy
    @busca.destroy!

    respond_to do |format|
      format.html { redirect_to buscas_path, notice: "Busca was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busca
      @busca = Busca.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def busca_params
      params.expect(busca: [ :perfil_id ])
    end
end

app/helpers/buscas_helper.rb
module BuscasHelper

    def circulo_status(status)
        case status
        when "pendente"
            "&#x1F7E1"
        when "processando"
            "&#x1F7E0"
        when "completa"
            "&#x1F7E2"
        when "erro"
            "&#x1F534"
        end.html_safe
    end
end

app/views/buscas/_busca.html.erb
<div id="<%= dom_id busca %>">
  <p>
    <strong>Perfil:</strong>
    <%= busca.perfil_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= busca.status %>
  </p>

  <p>
    <strong>Mensagem:</strong>
    <%= busca.mensagem %>
  </p>

  <p>
    <strong>Dados:</strong>
    <%= busca.dados %>
  </p>

</div>

app/views/buscas/_form.html.erb
<%= form_with(model: busca) do |form| %>
  <% if busca.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(busca.errors.count, "error") %> prohibited this busca from being saved:</h2>

      <ul>
        <% busca.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :perfil_id, style: "display: block" %>
    <%= form.number_field :perfil_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :mensagem, style: "display: block" %>
    <%= form.text_field :mensagem %>
  </div>

  <div>
    <%= form.label :dados, style: "display: block" %>
    <%= form.text_field :dados %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buscas/edit.html.erb
<% content_for :title, "Editing busca" %>

<h1>Editing busca</h1>

<%= render "form", busca: @busca %>

<br>

<div>
  <%= link_to "Show this busca", @busca %> |
  <%= link_to "Back to buscas", buscas_path %>
</div>

app/views/buscas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Buscas" %>

<h1>Buscas</h1>

<div id="buscas">
  <% @buscas.each do |busca| %>
    <%= render busca %>
    <p>
      <%= link_to "Show this busca", busca %>
    </p>
  <% end %>
</div>

<%= link_to "New busca", new_busca_path %>

app/views/buscas/new.html.erb
<% content_for :title, "New busca" %>

<h1>New busca</h1>

<%= render "form", busca: @busca %>

<br>

<div>
  <%= link_to "Back to buscas", buscas_path %>
</div>

app/views/buscas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @busca %>

<div>
  <%= link_to "Edit this busca", edit_busca_path(@busca) %> |
  <%= link_to "Back to buscas", buscas_path %>

  <%= button_to "Destroy this busca", @busca, method: :delete %>
</div>